Repository EveryUniv/next-student-council-frontend, pull requests merged in 2024-03, with the labels that each got.

#75 chore: 회원정보 업데이트 페이지 버튼 타입 수정
  src/pages/mypage/update.tsx
Labels: 🧑‍🔧 핫픽스

#78 chore: 네비게이션 수정
  src/components/common/nav/index.tsx
  src/components/main/menu.tsx
Labels: 🤩 개선 사항

#81 chore: 게시판 개선
  src/api/upload/types/upload.ts
  src/api/upload/upload.ts
  src/assets/images/organization-01.jpg
  src/assets/images/organization-02.jpg
  src/components/common/board/index.tsx
  src/components/common/carousel/index.tsx
  src/components/common/gnh/index.tsx
  src/components/main/menu.tsx
  src/components/main/post.tsx
  src/components/ui/box/PostBox.tsx
  src/components/ui/box/index.tsx
  src/components/ui/chart/PetitionChartList.tsx
  src/constants/heading.ts
  src/hooks/query/upload/mutation.ts
  src/hooks/useFormUpload.ts
  src/hooks/useImageUpload.tsx
  src/layouts/BoardLayout.tsx
  src/layouts/PostDetailLayout.tsx
  src/layouts/SinglePageLayout.tsx
  src/pages/conference/index.tsx
  src/pages/council/index.tsx
  src/pages/council/location.tsx
  src/pages/council/organization.tsx
  src/pages/council/recruitment.tsx
  src/pages/notice/[id].tsx
  src/pages/notice/index.tsx
  src/pages/notice/post.tsx
  src/pages/petition/[id].tsx
  src/pages/petition/index.tsx
  src/pages/petition/post.tsx
  src/pages/rule/index.tsx
Labels: 🤩 개선 사항

#85 refactor: selector 추가
  src/assets/icons/IconSprite.svg
  src/components/common/gnb/index.tsx
  src/components/common/gnh/index.tsx
  src/components/common/icon/SvgIcon.tsx
  src/components/main/cafeteria.tsx
  src/components/ui/button/IconButton.tsx
  src/components/ui/selector/index.tsx
  src/constants/route.ts
  src/layouts/DefaultLayout.tsx
  src/pages/reset/resetId.tsx
  src/pages/reset/resetPw.tsx
  src/pages/reset/verifyPw.tsx
  src/pages/signup/info.tsx
  src/pages/signup/success.tsx
Labels: ➕기능 추가

#92 fix: base 태그 추가
  public/index.html
Labels: 🧑‍🔧 핫픽스
