Repository EveryUniv/next-student-council-frontend, pull requests merged in 2024-01, with the labels that each got.

#54 Feat: 공지사항 페이지
  src/Router.tsx
  src/components/common/board/index.tsx
  src/components/common/carousel/arrowButton.tsx
  src/components/common/carousel/index.tsx
  src/components/ui/collapse/index.tsx
  src/components/ui/text/board.tsx
  src/layouts/BoardLayout.tsx
  src/pages/notice/[id].tsx
  src/pages/notice/index.tsx
  src/pages/petition/index.tsx
Labels: ➕기능 추가

#65 feat: 회의록 & 회칙 페이지
  package-lock.json
  src/PrivateRoute.tsx
  src/Router.tsx
  src/api/auth.ts
  src/components/common/board/index.tsx
  src/components/main/cafeteria.tsx
  src/constant.ts
  src/layouts/BoardLayout.tsx
  src/layouts/Delay.tsx
  src/pages/conference/index.tsx
  src/pages/petition/[id].tsx
  src/pages/rule/index.tsx
  yarn.lock
Labels: ➕기능 추가

#68 refactor: 회의록 & 회칙 페이지 리팩토링
  src/components/ui/text/board.tsx
  src/layouts/BoardLayout.tsx
  src/pages/conference/index.tsx
  src/pages/notice/index.tsx
  src/pages/petition/index.tsx
  src/pages/rule/index.tsx
  src/shared/function/generateDate.ts
Labels: 🤩 개선 사항

#66 feat: 사이드 메뉴바 구현 및 레이아웃 변경
  package.json
  src/PrivateRoute.tsx
  src/Router.tsx
  src/__test__/login.test.tsx
  src/assets/icons/IconSprite.svg
  src/assets/icons/breakfast.svg
  src/assets/icons/chevron_right.svg
  src/assets/icons/dinner.svg
  src/assets/icons/document.svg
  src/assets/icons/logo.svg
  src/assets/icons/profile.svg
  src/assets/icons/signup_success.svg
  src/components/common/gnb/index.tsx
  src/components/common/gnh/index.tsx
  src/components/common/icon/SvgIcon.tsx
  src/components/common/nav/index.tsx
  src/components/main/cafeteria.tsx
  src/components/main/service.tsx
  src/constants/api.ts
  src/constants/route.ts
  src/constants/style.ts
  src/hooks/useAuth.tsx
  src/hooks/useLayout.tsx
  src/layouts/DefaultLayout.tsx
  src/pages/conference/index.tsx
  src/pages/council/index.tsx
  src/pages/council/location.tsx
  src/pages/council/organization.tsx
  src/pages/council/recruitment.tsx
  src/pages/index.tsx
  src/pages/login.tsx
  src/pages/menu.tsx
  src/pages/mypage.tsx
  src/pages/notice/[id].tsx
  src/pages/notice/index.tsx
  src/pages/notice/post.tsx
  src/pages/petition/[id].tsx
  src/pages/petition/index.tsx
  src/pages/petition/post.tsx
  src/pages/rental/index.tsx
  src/pages/rule/index.tsx
  src/pages/signup/info.tsx
  src/pages/signup/terms.tsx
  src/pages/signup/verify.tsx
  src/stores/gnh-store.ts
  src/stores/nav-store.ts
  tailwind.config.js
Labels: ➕기능 추가, 🤩 개선 사항

#70 fix: 반영안된 constant 수정
  src/hooks/useApi.ts
Labels: 🐜 버그

#69 feat: 회원 정보 페이지
  src/Router.tsx
  src/components/mypage/edit.tsx
  src/components/ui/button/index.tsx
  src/components/ui/input/index.tsx
  src/constants/api.ts
  src/constants/route.ts
  src/constants/style.ts
  src/data/mypage/edit/defaultFormInfo.ts
  src/hooks/useAuth.tsx
  src/hooks/useLayout.tsx
  src/interfaces/mypage/edit.ts
  src/layouts/MyPageLayout.tsx
  src/pages/mypage.tsx
  src/pages/mypage/edit.tsx
  src/pages/mypage/index.tsx
  src/pages/mypage/password.tsx
  src/utils/checkInputRegex.ts
  tailwind.config.js
Labels: ➕기능 추가
